### PR TITLE
Fix error when calling setFields with an array

### PR DESCRIPTION
**Pull request by edbizarro**
fix error "You must pass either an array or an instance of Spatie\SlashCommand\AttachmentField" in setFields method.

The error is caused by a incompatible signature on addField method

### CODE REVIEW

**Comment by freekmurze** [comment]
According to the docs the `$key` is the second parameter of `each`.

**Comment by edbizarro** [comment]
hi @freekmurze , thx for your feedback.

In this line https://github.com/spatie/laravel-slack-slash-command/blob/master/src/Attachment.php#L359 the AttachmentField::create is called with an array, but 2 params is expected and ends up throwing an error

And about the 'each', you mean in the Laravel docs?

**Comment by freekmurze** [comment]
I've made [an easier fix](https://github.com/spatie/laravel-slack-slash-command/commit/d1308117f50283ee84fd6a7baeb6df78bb0299ef). Could you let me know if the current `dev-master` branch works ok for you?

**Comment by edbizarro** [comment]
works with an array with only 1 index, with more elements only the first one is used.

My work case:

Array
(
   [author] => Eduardo Bizarro
   [message] => lock file
   [url] => url
)

with your fix i get just the author

**Comment by freekmurze** [comment]
And if you pass your array to `setFields`?

**Comment by edbizarro** [comment]
same error message

screenshot from 2016-10-17 12-52-29

in [this block](https://github.com/spatie/laravel-slack-slash-command/pull/35/files#diff-3a9a9ecefb5ce18a6a1a77052a5c209eR360) i handle this case

**Comment by freekmurze** [comment]
The tests seem to prove that the newly added function `addFields` should work.

https://github.com/spatie/laravel-slack-slash-command/blob/master/tests/AttachmentTest.php

If not, please submit a failing test.

**Comment by edbizarro** [comment]
nice, i'll take a look and submit the tests :D

now seems the setFields stop working at all

**Comment by freekmurze** [comment]
Pushed some more commits to the master branch. Let me know if this works for you.

**Comment by edbizarro** [comment]
yeah, works like a charm, tks for your support :smiley:

**Pull request closed without merging**
